[workspace]
name = "my-workspace"

[settings]
git_fetch_with_cli = false
parallel = 4
shallow = false
manage_gitignore = true
manage_vscode = true

[repos]
test-repo = { url = "file://./crates/un-cli/tests/test_data/source", path = "crates/un-cli/tests/repos/test-repo" }
